name: aitor

services:
    qdrant:
        image: qdrant/qdrant:latest
        restart: always
        container_name: qdrant
        ports:
            - "6333:6333"
            - "6334:6334"
        expose:
            - 6333
            - 6334
            - 6335
        configs:
            -   source: qdrant_config
                target: /qdrant/config/production.yaml
        volumes:
            - ./qdrant_data:/qdrant/storage
    mongo:
        image: mongo:8
        ports:
            - "27017:27017"
        volumes:
            - ./mongo_data:/var/lib/mongodb/data

configs:
    qdrant_config:
        content: |
            log_level: INFO