spring:
    application:
        name: aitor
    ai:
        ollama:
            base-url: "http://localhost:11434"
            embedding:
                enabled: true
                options:
                    model: mxbai-embed-large
        qdrant:
            initializeSchema: true
            batching-strategy: TOKEN_COUNT
bot:
    api-token: ${BOT_TOKEN}
    name: "KekitaBot"